export const WEATHER_TYPE_DESC = {
  1: "Céu limpo",
  2: "Céu pouco nublado",
  3: "Céu parcialmente nublado",
  4: "Céu muito nublado",
  5: "Aguaceiros",
  6: "Aguaceiros com trovoada",
  7: "Chuva",
  8: "Chuva com trovoada",
  9: "Neve",
  10: "Aguaceiros de neve",
  11: "Nevoeiro",
  12: "Chuviscos",
  13: "Chuva fraca",
  14: "Aguaceiros fracos",
  15: "Neblina",
  16: "Aguaceiros fracos",
  17: "Trovoada",
  18: "Aguaceiros com granizo",
  19: "Aguaceiros com granizo e trovoada",
  20: "Granizo",
  21: "Neve com aguaceiros",
  22: "Neve com trovoada",
  23: "Geada",
  24: "Chuva gelada",
  25: "Nevoeiro denso",
};
